# -*- coding: utf-8 -*-
"""Szvetkó-kampusz: jogvédett nevek cseréje. A sorrend SZÁMÍT (leghosszabb előbb)."""

# (regex, csere) párok — sorrendben alkalmazva
SZOTAR = [
    # ---------- 0. Egyedi mondatok, amiket nem lehet gépiesen cserélni ----------
    (r'Ha Bruce Banner ideges lesz, akkor Hulkká változik\.',
     'Ha Banner Brúnó ideges lesz, akkor zöldre változik.'),
    (r'Ha Thanos megszerzi mind a hat követ, akkor csettinthet\.',
     'Ha Kán megszerzi mind a hat kulcsot, akkor átírhatja az egyenletet.'),
    (r'mintha Thanos tüsszentett volna a papírra',
     'mintha egy óriás tüsszentett volna a papírra'),
    (r'Nat kém és harcművész\.', 'Nada kém és harcművész.'),
    (r'Ez a <b>Danger Room</b> — a kampusz szimulációs edzőterme \(a technológiát a Xavier-intézet X-Menjeitől licenceltük\)\.',
     'Ez a kampusz szimulációs edzőterme (a technológiát az X. Károly Intézet Mutáns Osztagától licenceltük).'),
    (r'A Marvel „Avengers Academy” ötletére',
     'A „hősakadémia” ötletére'),
    (r'A Marvel „Avengers Academy" ötletére',
     'A „hősakadémia” ötletére'),
    (r'\(JARVIS/FRIDAY-szerű\)', '(filmes MI-asszisztensekre emlékeztető)'),
    (r'JARVIS/FRIDAY-szerű', 'filmes MI-asszisztensekre emlékeztető'),
    (r'egy Mad Max-szerű pusztaságra', 'egy poszt-apokaliptikus pusztaságra'),
    (r'Mad Max-szerű', 'poszt-apokaliptikus'),
    (r'Amikor Scott Ant-Manné zsugorodik', 'Amikor Henrik hangyaméretűre zsugorodik'),
    (r'a valódi Scott\b', 'a valódi Henrik'),
    (r'Hope van Dyne &amp; Hank Pym', 'Darázs Dorka &amp; Hangya Henrik'),
    (r'Hope van Dyne & Hank Pym', 'Darázs Dorka & Hangya Henrik'),
    (r'Hope van Dyne', 'Darázs Dorka'),
    (r'Ant-Man \(Hank Pym\)', 'Hangya Henrik'),
    (r'Hank Pym', 'Hangya Henrik'),

    # ---------- 1. Szervezetek, helyszínek (leghosszabb előbb) ----------
    (r'S\.H\.I\.E\.L\.D\.\s*akadémia', 'S.Z.V.E.T.I. Központ'),
    (r'S\.H\.I\.E\.L\.D\.', 'S.Z.V.E.T.I. Központ'),
    (r'S\.H\.I\.E\.L\.D\b', 'S.Z.V.E.T.I. Központ'),
    (r'SHIELD', 'SZVETI'),

    (r'Avengers Akadémia', 'a Hősök Ligájának Akadémiája'),
    (r'Avengers Academy', 'Hősök Ligája Akadémia'),
    (r'Avengers-univerzum', 'Liga-univerzum'),
    (r'Avengers-akták', 'Liga-akták'),
    (r'Avengers-torony', 'Liga-torony'),
    (r'Avengers-toborzó', 'Liga-toborzó'),
    (r'Avengers-', 'Liga-'),
    (r'\bAvengers\b', 'Hősök Ligája'),
    (r'\bAvenger\b', 'ligatag'),

    (r'X-Menjeitől', 'Mutáns Osztagától'),
    (r'X-Men', 'Mutáns Osztag'),
    (r'X-Faktor', 'M-Faktor'),
    (r'X-Gén', 'M-Gén'),

    (r'Xavier-intézet', 'X. Károly Intézet'),
    (r'Charles Xavier \(Professor X\)', 'X. Károly professzor'),
    (r'Charles Xavier', 'X. Károly'),
    (r'Professor X', 'X. Károly professzor'),
    (r'\bXavier\b', 'X. Károly'),

    (r'Inhuman-sztori', 'Különlegesek-sztori'),
    (r'Inhumanek', 'Különlegesek'),
    (r'\bInhumans\b', 'A Különlegesek'),
    (r'ősi Inhuman ereklye', 'ősi különleges ereklye'),
    (r'\bInhuman\b', 'Különleges'),

    (r'\bTVA\b', 'I.V.H.'),
    (r'Time Variance Authority', 'Idővonal Védelmi Hivatal'),

    (r'Danger Room \(Veszélyterem\)', 'Vészterem'),
    (r'\(Danger Room\)', '(Vészterem)'),
    (r'Danger Room', 'Vészterem'),
    (r'Veszélyterem', 'Vészterem'),

    (r'Cerebro-keresés', 'UMOTRON-keresés'),
    (r'Cerebro-hátterű', 'UMOTRON-hátterű'),
    (r'CEREBRO', 'UMOTRON'),
    (r'Cerebro', 'UMOTRON'),

    (r'Genoshai', 'Geno-szigeti'),
    (r'Genosha', 'Geno-sziget'),
    (r'Attilan', 'Kristályvár'),

    (r'Terrigen-anomáliává', 'Kristálypára-anomáliává'),
    (r'Terrigen-anomália', 'Kristálypára-anomália'),
    (r'Terrigen-generátorra', 'Kristálypára-generátorra'),
    (r'Terrigen-elemzés', 'Kristály-elemzés'),
    (r'Terrigen-kamra', 'Kristály-kamra'),
    (r'Terrigen Karantén-Zóna', 'Kristály Karantén-Zóna'),
    (r'Terrigen', 'Kristálypára'),

    (r'Pym-protokollhoz', 'Zsugor-protokollhoz'),
    (r'Pym-protokollra', 'Zsugor-protokollra'),
    (r'Pym-protokoll', 'Zsugor-protokoll'),
    (r'Pym-részecskék', 'zsugor-részecskék'),
    (r'Pym-részecske', 'zsugor-részecske'),
    (r'Pym-skálázás', 'zsugor-skálázás'),
    (r'\bPym\b', 'Henrik'),

    (r'Chimichanga-matek', 'Burek-matek'),
    (r'chimichanga-melegítéssel', 'burek-melegítéssel'),
    (r'Chimichanga', 'Burek'),
    (r'chimichangát', 'bureket'),
    (r'chimichanga', 'burek'),
    (r'Maximum Effort', 'Maximális erőbedobás'),

    # ---------- 2. Karakterek — hosszú alakok előbb ----------
    (r'Nick Fury', 'Nikola Furić parancsnok'),
    (r'\bFury\b', 'Furić'),

    (r'Tony Stark / Iron Man', 'Krats Ynot'),
    (r'Tony Stark', 'Krats Ynot'),
    (r'Stark-reaktor', 'Ynot-reaktor'),
    (r'\bStark\b', 'Ynot'),
    (r'Iron Man', 'Krats Ynot'),

    (r'Peter Parkert', 'Petar Paukot'),
    (r'Peter Parker', 'Petar Pauk'),
    (r'\bParkert\b', 'Paukot'),
    (r'Spider-Manre', 'Petar Paukra'),
    (r'Spider-Man', 'Petar Pauk'),
    (r'Spider-taxi', 'Pauk-taxi'),
    (r'Spider-háló', 'Pauk-háló'),
    (r'id="spider"', 'id="pauk"'),

    (r'Loki-kapuk', 'Ikol-kapuk'),
    (r'id="loki-csapda"', 'id="ikol-csapda"'),
    (r'id="loki"', 'id="ikol"'),
    (r'\bLoki\b', 'Ikol'),

    (r'Doctor Strange', 'Dr. Bizarr'),
    (r'strange-descartes', 'bizarr-descartes'),
    (r'strange-sajat', 'bizarr-sajat'),
    (r'strange-fix', 'bizarr-fix'),
    (r'\bStrange\b', 'Dr. Bizarr'),

    (r'Clint Barton', 'Barton Kálmán'),
    (r'Hawkeye / Clint Barton', 'Barton Kálmán'),
    (r'\bHawkeye\b', 'Barton Kálmán'),

    (r'Carol Danvers / Captain Marvel', 'Denveri Karolina'),
    (r'Captain Marvel', 'Denveri Karolina'),
    (r'Carol Danvers', 'Denveri Karolina'),
    (r'\bDanvers\b', 'Denveri Karolina'),

    (r'Bruce Banner', 'Banner Brúnó'),
    (r'Hulk-bevetés', 'Brúnó-bevetés'),
    (r'hulk-bevetes', 'bruno-bevetes'),
    (r'class="sav hulk"', 'class="sav bruno"'),
    (r'"sav hulk"', '"sav bruno"'),
    (r'sav hulk', 'sav bruno'),
    (r'\.sav\.hulk', '.sav.bruno'),
    (r'\bHulk\b', 'Brúnó'),

    (r'Ant-Man &amp; The Wasp', 'Hangya Henrik &amp; Darázs Dorka'),
    (r'Ant-Man & The Wasp', 'Hangya Henrik & Darázs Dorka'),
    (r'Ant-Man-bevetés', 'Henrik-bevetés'),
    (r'ant-man-bevetes', 'henrik-bevetes'),
    (r'Ant-Man-makett', 'Hangya-makett'),
    (r'Ant-Manné', 'hangyaméretűvé'),
    (r'Ant-Man', 'Hangya Henrik'),
    (r'Hangya-bevetés', 'Henrik-bevetés'),
    (r'class="sav hangya"', 'class="sav henrik"'),
    (r'"sav hangya"', '"sav henrik"'),
    (r'sav hangya', 'sav henrik'),
    (r'\.sav\.hangya', '.sav.henrik'),

    (r'The Wasp', 'Darázs Dorka'),
    (r'\bWasp\b', 'Darázs Dorka'),

    (r'Scarlet Witch &amp; Quicksilver', 'Vanda &amp; Fürge Pjotr'),
    (r'Scarlet Witch & Quicksilver', 'Vanda & Fürge Pjotr'),
    (r'Scarlet Witch', 'Vanda'),
    (r'\bScarlet\b', 'Vanda'),
    (r'Quicksilver', 'Fürge Pjotr'),

    (r'Shurival', 'Iruhsszal'),
    (r'Shuri &amp; Iron Man', 'Iruhs &amp; Krats Ynot'),
    (r'Shuri & Iron Man', 'Iruhs & Krats Ynot'),
    (r'\bShuri\b', 'Iruhs'),

    (r'Kang-csapdaként', 'Kán-csapdaként'),
    (r'Kang-csapda', 'Kán-csapda'),
    (r'kang-glitch', 'kan-glitch'),
    (r'Kang-glitch', 'Kán-glitch'),
    (r'Kang, a Hódító', 'Kán, a Hódító'),
    (r'\bKang\b', 'Kán'),

    # --- 2. évad ---
    (r'Logan \(Wolverine\)', 'Nagol hadnagy'),
    (r'Wolverine / Logan', 'Nagol hadnagy'),
    (r'Deadpool & Wolverine', 'Véd Vilmos & Nagol'),
    (r'Deadpool &amp; Wolverine', 'Véd Vilmos &amp; Nagol'),
    (r'\bWolverine\b', 'Nagol'),
    (r'\bLogan\b', 'Nagol'),

    (r'\bStorm\b', 'Vihar Vera'),

    (r'Hank McCoy \(Beast\)', 'Dr. Bestia'),
    (r'Beast / Hank McCoy', 'Dr. Bestia'),
    (r'Hank McCoy', 'Dr. Bestia'),
    (r'\bMcCoy\b', 'Dr. Bestia'),
    (r'Beast-protokoll', 'Bestia-protokoll'),
    (r'\bBeast\b', 'Dr. Bestia'),

    (r'\bCyclops\b', 'Küklopsz'),
    (r'\bMagneto\b', 'Magnetron'),
    (r'Jean Grey', 'Szürke Janka'),
    (r'\bJean\b', 'Janka'),

    (r'Mister Sinister', 'Dr. Baljós'),
    (r'Sinister-bázisról', 'Baljós-bázisról'),
    (r'Sinister-bázist', 'Baljós-bázist'),
    (r'Sinister-bázis', 'Baljós-bázis'),
    (r'Sinistert\b', 'Dr. Baljóst'),
    (r'\bSinister\b', 'Dr. Baljós'),

    (r'Phoenix-protokoll', 'Főnix-protokoll'),
    (r'\bPhoenix\b', 'Főnix'),

    # --- 3. évad ---
    (r'Black Bolt', 'Crni Grom'),
    (r'\bMedusa\b', 'Medúza'),
    (r'\bKarnak\b', 'Kanrak'),
    (r'\bCrystal\b', 'Prizma'),
    (r'Lockjaw-ugrás', 'Tér-eb-ugrás'),
    (r'\bLockjaw\b', 'Tér-eb'),
    (r'Maximus the Mad', 'Maxi, az Őrült'),
    (r'Maximus, az Őrült', 'Maxi, az Őrült'),
    (r'\bMaximus\b', 'Maxi'),

    # --- 4. évad ---
    (r'Wade Wilson \(Deadpool\)', 'Véd Vilmos'),
    (r'Deadpool / Wade Wilson', 'Véd Vilmos'),
    (r'Wade Wilson', 'Véd Vilmos'),
    (r'deadpool-csapda', 'vilmos-csapda'),
    (r'Deadpool-variáns', 'Vilmos-variáns'),
    (r'Deadpoollal', 'Véd Vilmossal'),
    (r'Deadpoolt\b', 'Véd Vilmost'),
    (r'\bDeadpool\b', 'Véd Vilmos'),

    (r'O\.B\. \(Ouroboros\)', 'Uroborosz'),
    (r'\bOuroboros\b', 'Uroborosz'),
    (r'(?<![A-Za-z])O\.B\.', 'Uroborosz'),
    (r'\bDogpool\b', 'Véd-eb'),
    (r'\bBabypool\b', 'Mini-Vili'),
    (r'\bNicepool\b', 'Nyalka Vili'),
    (r'Mr\. Paradox', 'Mr. Szürreál'),
    (r'\bParadox\b(?!on)', 'Mr. Szürreál'),

    # ---------- 3. „Marvel” mint márkanév + CSS-változók ----------
    (r'--marvel-green-neon', '--kampusz-neon'),
    (r'--marvel-green-dark', '--kampusz-sotet'),
    (r'--marvel-glass-border', '--kampusz-uveg-keret'),
    (r'--marvel-glass-bg', '--kampusz-uveg'),
    (r'--marvel-glow', '--kampusz-fenylés'),
    (r'btn-marvel', 'btn-kampusz'),
    (r'marvelesített', 'képregényesített'),
    (r'Marvel-köntösben', 'kampusz-köntösben'),
    (r'Marvel-köntös', 'kampusz-köntös'),
    (r'Marvel-stílusú', 'képregényes stílusú'),
    (r'Marvel-filmet', 'képregényfilmet'),
    (r'Marvel-ízű', 'képregényes ízű'),
    (r'MARVEL', 'KAMPUSZ'),
    (r'\bMarvel\b', 'saját'),
    (r'\bThanos\b', 'Kán'),

    # ---------- 4. Második kör: a szótárban nem szereplő további nevek ----------
    (r'Krats Ynot \(Krats Ynot\)', 'Krats Ynot'),
    (r'Hangya Henrik &amp; Hangya Henrik', 'Hangya Henrik &amp; Darázs Dorka'),
    (r'Darázs Dorka \(Darázs Dorka\)', 'Darázs Dorka'),
    (r'Vanda \(Wanda\)', 'Vanda'),
    (r'Fürge Pjotr \(Pietro\)', 'Fürge Pjotr'),
    (r'Hangya Henrik \(Scott Lang\)', 'Hangya Henrik'),
    (r'Scott Lang', 'Hangya Henrik'),
    (r'\bNightcrawler\b', 'Éjjáró'),
    (r'Captain America', 'Pajzs kapitány'),
    (r'Black Widow', 'Nada'),
    (r'\bWanda\b', 'Vanda'),
    (r'\bPietro\b', 'Fürge Pjotr'),
]

# Magyar határozott névelő igazítása a megváltozott kezdőhangokhoz
NEVELO_AZ = [r'UMOTRON', r'I\.V\.H\.', r'S\.Z\.V\.E\.T\.I\.', r'X\. Károly',
             r'Uroborosz', r'M-Faktor', r'M-Gén', r'Ikol', r'Iruhs', r'Őrült', r'Éjjáró']
NEVELO_A = [r'Hősök Ligája', r'Mutáns Osztag', r'Különlegesek', r'Vészterem', r'Kristályvár',
            r'Kristálypára', r'Geno-sziget', r'Zsugor-protokoll', r'Burek', r'Maximális erőbedobás',
            r'Nikola Furić', r'Krats Ynot', r'Petar Pauk', r'Barton Kálmán', r'Dr\. Bizarr',
            r'Denveri Karolina', r'Banner Brúnó', r'Brúnó', r'Hangya Henrik', r'Darázs Dorka',
            r'Vanda', r'Fürge Pjotr', r'Kán', r'Nagol', r'Vihar Vera', r'Dr\. Bestia', r'Küklopsz',
            r'Magnetron', r'Szürke Janka', r'Dr\. Baljós', r'Baljós', r'Főnix', r'Crni Grom',
            r'Medúza', r'Kanrak', r'Prizma', r'Tér-eb', r'Maxi', r'Véd Vilmos', r'Véd-eb',
            r'Mini-Vili', r'Nyalka Vili', r'Mr\. Szürreál', r'Bestia', r'Henrik', r'Vilmos',
            r'Pauk', r'Ynot', r'Janka', r'Pajzs kapitány', r'Nada']

# Karakter → (négyzetes kép, fekvő kép vagy None)
KEPEK = {
    'SZVETI':            ('svetozar.webp', None),
    'Ikol':              ('ikol.jpeg', 'ikol_2.jpeg'),
    'Dr. Bizarr':        ('dr_bizarr.jpeg', 'dr_bizarr_2.jpeg'),
    'Petar Pauk':        ('pauk_petar.jpeg', 'pauk_petar_2.jpeg'),
    'Barton Kálmán':     ('barton_kalman.jpeg', 'barton_kalman_2.jpeg'),
    'Iruhs':             ('iruhs.jpeg', None),
    'Banner Brúnó':      ('banner_bruno.jpeg', 'banner_bruno_2.jpeg'),
    'Banner':            ('banner_bruno.jpeg', 'banner_bruno_2.jpeg'),
    'Hangya Henrik':     ('hangya_henrik.jpeg', None),
    'Darázs Dorka':      ('darazs_dorka.jpeg', None),
    'Vanda':             ('vanda.jpeg', None),
    'Fürge Pjotr':       ('furge_pjotr.jpeg', 'furge_pjotr_2.jpeg'),
    'Krats Ynot':        ('krats_ynot.jpeg', 'krats_ynot_2.jpeg'),
    'Denveri Karolina':  ('denveri_karolina.jpeg', None),
    'Nikola Furić parancsnok': ('furic_nikola.jpeg', None),
    'Nikola Furić':      ('furic_nikola.jpeg', None),
    'X. Károly professzor': ('x_karoly.jpeg', 'x_karoly_2.jpeg'),
    'X. Károly':         ('x_karoly.jpeg', 'x_karoly_2.jpeg'),
    'Nagol hadnagy':     ('nagol.jpeg', 'nagol_2.jpeg'),
    'Nagol':             ('nagol.jpeg', 'nagol_2.jpeg'),
    'Vihar Vera':        ('vihar_vera.jpeg', None),
    'Dr. Bestia':        ('dr_bestia.jpeg', None),
    'Küklopsz':          ('küklopsz.jpeg', None),
    'Magnetron':         ('magnetron.jpeg', 'magnetron_2.jpeg'),
    'Szürke Janka':      ('szurke_janka.jpeg', None),
    'Crni Grom':         ('crni_grom.jpeg', None),
    'Medúza':            ('meduza.jpeg', None),
    'Kanrak':            ('kanrak.jpeg', None),
    'Prizma':            ('prisma.jpeg', None),
    'Tér-eb':            ('ter_eb.jpeg', None),
    'Véd Vilmos':        ('ved_vilmos.jpeg', 'ved_vilmos_2.jpeg'),
    'Véd-eb':            ('ved_eb.jpeg', None),
    'Mini-Vili':         ('baby_vili.jpeg', None),
}

# rövid jellemzés az alt-szöveghez
ALT = {
    'SZVETI': 'a Szvetkó-kampusz mesterséges intelligenciája',
    'Ikol': 'az igaz és a hamis mestere',
    'Dr. Bizarr': 'a multiverzum térképésze',
    'Petar Pauk': 'a hálók és függvények mestere',
    'Barton Kálmán': 'a kampusz céllövő oktatója',
    'Iruhs': 'a kampusz fejlesztőmérnöke',
    'Banner Brúnó': 'a mérés és a hibabecslés tudósa',
    'Banner': 'a mérés és a hibabecslés tudósa',
    'Hangya Henrik': 'a méretarányok szakértője',
    'Darázs Dorka': 'a Zsugor-protokoll pilótája',
    'Vanda': 'a valóságformálás mestere',
    'Fürge Pjotr': 'a kampusz leggyorsabb kadétja',
    'Krats Ynot': 'a kampusz fővezető mérnöke',
    'Denveri Karolina': 'kiképzőtiszt',
    'Nikola Furić parancsnok': 'az Akadémia igazgatója',
    'Nikola Furić': 'az Akadémia igazgatója',
    'X. Károly professzor': 'a Mutáns Osztag alapítója',
    'X. Károly': 'a Mutáns Osztag alapítója',
    'Nagol hadnagy': 'a morcos kiképzőtiszt',
    'Nagol': 'a morcos kiképzőtiszt',
    'Vihar Vera': 'az időjárás úrnője',
    'Dr. Bestia': 'a kampusz fővezető tudósa',
    'Küklopsz': 'az optikai sugarak mestere',
    'Magnetron': 'a mágneses mezők ura',
    'Szürke Janka': 'a telepata bemérő-specialista',
    'Crni Grom': 'a Néma Király',
    'Medúza': 'a Királyi Család hangja',
    'Kanrak': 'a rendszerek és töréspontok mestere',
    'Prizma': 'a térgeometria oktatótisztje',
    'Tér-eb': 'a teleportáló kutya',
    'Véd Vilmos': 'a negyedik falat áttörő zsoldos',
    'Véd-eb': 'a nyomravezető kutya',
    'Mini-Vili': 'a legkisebb variáns',
}
